#  Assignment 5: Data Analysis using NumPy and Pandas

## 1. Create a 1D NumPy Array

In [1]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


## 2. Inspection and Properties

In [2]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7


## 3. Array Operations

In [3]:
temperatures_f = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:")
print(temperatures_f)

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


### Find the Maximum, Minimum, and Mean Temperatures

In [4]:
print("Maximum Temperature:", np.max(temperatures_w1))
print("Minimum Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", np.mean(temperatures_w1))

Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


## 4. Array Slicing and Indexing

In [5]:
first_three_days = temperatures_w1[:3]

print("First Three Days:")
print(first_three_days)

First Three Days:
[22.5 25.3 20.8]


### Weekend Temperatures

In [6]:
weekend = temperatures_w1[-2:]

print("Weekend Temperatures:")
print(weekend)

Weekend Temperatures:
[24.8 21.9]


### Middle Three Days

In [7]:
middle_three_days = temperatures_w1[2:5]

print("Middle Three Days:")
print(middle_three_days)

Middle Three Days:
[20.8 23.4 26.1]


## 5. Create a 2D Array

In [8]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


## 6. Inspect and Slice the 2D Array

In [9]:
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)

Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14


### Extract Temperatures for Each Week

In [10]:
week1 = temperatures[0]
week2 = temperatures[1]

week1_weekend = temperatures[0, -2:]
week2_weekend = temperatures[1, -2:]

print("Week 1:", week1)
print("Week 2:", week2)

print("Week 1 Weekend:", week1_weekend)
print("Week 2 Weekend:", week2_weekend)

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 Weekend: [24.8 21.9]
Week 2 Weekend: [22.8 20.1]


# Pandas Series

## 1. Creating Pandas Series

In [11]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


## 2. Indexing and Slicing

In [12]:
print("Mark of 1st Rank Student:", marks.iloc[0])

Mark of 1st Rank Student: 95


### Retrieve the Top 3 Ranks

In [13]:
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


### Retrieve the 3rd Rank Student

In [14]:
print("Mark of 3rd Rank Student:", marks.iloc[2])

Mark of 3rd Rank Student: 89


### Boolean Mask

In [15]:
print(marks[marks > 90])

Rank1    95
Rank2    92
dtype: int64


## 3. Manipulating Series

In [16]:
marks.loc['Rank1'] = 100

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


### Remove the Last Rank

In [17]:
marks = marks.drop('Rank5')

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


### Compute CGPA

In [18]:
cgpa = marks / 10

print("CGPA:")
print(cgpa)

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


# Pandas DataFrame

## 1. Creating Pandas DataFrame

In [19]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


## 2. Data Exploration

In [20]:
print("Transactions DataFrame:")
display(transactions)

print("First 5 Rows:")
display(transactions.head())

print("Last 5 Rows:")
display(transactions.tail())

print("Shape:", transactions.shape)

print("Column Names:")
print(transactions.columns)

print("Data Types:")
print(transactions.dtypes)

Transactions DataFrame:


,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


First 5 Rows:


,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200


Last 5 Rows:


,TransactionID,ProductCategory,Region,Amount
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


Shape: (10, 4)
Column Names:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')
Data Types:
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object


### Display ProductCategory and Amount

In [21]:
display(transactions[['ProductCategory', 'Amount']])

,ProductCategory,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


### Retrieve the Last 3 Columns


In [22]:
display(transactions.iloc[:, -3:])

,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


### Filter Rows

In [23]:
filtered_transactions = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

display(filtered_transactions)

,TransactionID,ProductCategory,Region,Amount
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


### Value Counts

In [24]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


### Unique Regions

In [25]:
print(transactions['Region'].unique())

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str


### Mean Amount by Region

In [26]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


## 3. Manipulating the DataFrame


In [27]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

display(transactions)

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


### Add Discount Column

In [28]:
transactions['Discount'] = transactions['Amount'] * 0.10

display(transactions)

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
8,109,Furniture,South,350,35.0
9,110,Electronics,North,400,40.0


### Remove Transaction 109

In [29]:
transactions = transactions[
    transactions['TransactionID'] != 109
]

display(transactions)

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


### Delete the Discount Column